stages:
  - lint
  - build
  - deploy

image: node:carbon

cache:
  paths:
  - node_modules/

lint:
  stage: lint
  script:
    - yarn lint

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 20 mins
  environment:
    name: production
  only:
    - master

deploy:
  image: python:3.6
  stage: deploy
  dependencies:
  - build
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export S3_BUCKET=$S3_BUCKET
    - pip install awscli --upgrade --user
    - export PATH=~/.local/bin:$PATH
    - aws s3 sync --acl public-read --delete dist $S3_BUCKET
  environment:
    name: production
  only:
    - master
